#!/usr/bin/env python3
"""
GUI Application Optimization Script

This script provides optimization recommendations and performance tuning
for the FractalSemantics GUI application.
"""

import sys
import psutil
import time
from pathlib import Path

def check_system_resources():
    """Check available system resources."""
    print("🔍 System Resource Analysis")
    print("=" * 40)
    
    # Memory information
    memory = psutil.virtual_memory()
    print(f"Total Memory: {memory.total / 1024 / 1024 / 1024:.2f} GB")
    print(f"Available Memory: {memory.available / 1024 / 1024 / 1024:.2f} GB")
    print(f"Memory Usage: {memory.percent}%")
    
    # CPU information
    cpu_count = psutil.cpu_count()
    cpu_freq = psutil.cpu_freq()
    print(f"CPU Cores: {cpu_count}")
    if cpu_freq:
        print(f"CPU Frequency: {cpu_freq.current:.0f} MHz (max: {cpu_freq.max:.0f} MHz)")
    
    # Disk space
    disk = psutil.disk_usage('/')
    print(f"Disk Space: {disk.total / 1024 / 1024 / 1024:.2f} GB total")
    print(f"Disk Free: {disk.free / 1024 / 1024 / 1024:.2f} GB free")
    
    return {
        'memory_gb': memory.total / 1024 / 1024 / 1024,
        'memory_available_gb': memory.available / 1024 / 1024 / 1024,
        'cpu_cores': cpu_count,
        'disk_free_gb': disk.free / 1024 / 1024 / 1024
    }

def analyze_dependencies():
    """Analyze dependency versions and potential optimizations."""
    print("\n📦 Dependency Analysis")
    print("=" * 40)
    
    try:
        import streamlit as st
        import plotly
        import pandas as pd
        import numpy as np
        
        print(f"✅ Streamlit: {st.__version__}")
        print(f"✅ Plotly: {plotly.__version__}")
        print(f"✅ Pandas: {pd.__version__}")
        print(f"✅ NumPy: {np.__version__}")
        
        # Check for performance optimizations
        if hasattr(np, 'show_config'):
            np.show_config()
        
        return True
        
    except ImportError as e:
        print(f"❌ Missing dependency: {e}")
        return False

def generate_optimization_recommendations(resources):
    """Generate optimization recommendations based on system resources."""
    print("\n⚡ Optimization Recommendations")
    print("=" * 40)
    
    recommendations = []
    
    # Memory recommendations
    if resources['memory_gb'] < 4:
        recommendations.append("⚠️  Low memory detected (< 4GB). Consider:")
        recommendations.append("   - Using Quick Mode for experiments")
        recommendations.append("   - Running fewer experiments in parallel")
        recommendations.append("   - Closing other applications")
    elif resources['memory_gb'] >= 8:
        recommendations.append("✅ Good memory capacity (≥ 8GB). Can handle:")
        recommendations.append("   - Full mode experiments")
        recommendations.append("   - Parallel execution")
        recommendations.append("   - Large datasets")
    
    # CPU recommendations
    if resources['cpu_cores'] < 4:
        recommendations.append("⚠️  Limited CPU cores (< 4). Consider:")
        recommendations.append("   - Sequential execution mode")
        recommendations.append("   - Quick mode experiments")
    elif resources['cpu_cores'] >= 4:
        recommendations.append("✅ Good CPU capacity (≥ 4 cores). Can handle:")
        recommendations.append("   - Parallel execution")
        recommendations.append("   - Multiple concurrent experiments")
    
    # Disk recommendations
    if resources['disk_free_gb'] < 1:
        recommendations.append("⚠️  Low disk space (< 1GB free). Consider:")
        recommendations.append("   - Cleaning up temporary files")
        recommendations.append("   - Moving results to external storage")
    
    for rec in recommendations:
        print(rec)
    
    return recommendations

def create_optimization_config():
    """Create an optimization configuration file."""
    print("\n⚙️  Creating Optimization Configuration")
    print("=" * 40)
    
    config_content = '''# GUI Application Optimization Configuration
# Generated by optimize_gui.py

[performance]
# Memory optimization settings
max_concurrent_experiments = 3
memory_warning_threshold_mb = 1000
auto_clear_results_after_hours = 24

# Visualization optimization
max_data_points_chart = 1000
chart_update_interval_seconds = 5
enable_chart_caching = true

# Experiment optimization
default_quick_mode = true
default_parallel_execution = true
max_experiment_duration_minutes = 30

[ui]
# Interface optimization
auto_refresh_enabled = true
auto_refresh_interval_seconds = 10
enable_progress_animations = true
chart_theme = "plotly_white"

[logging]
# Logging optimization
log_level = "INFO"
log_file_size_mb = 10
log_retention_days = 7
enable_performance_logging = true
'''
    
    config_file = Path("gui_optimization.toml")
    try:
        with open(config_file, 'w') as f:
            f.write(config_content)
        print(f"✅ Optimization config created: {config_file}")
        return True
    except Exception as e:
        print(f"❌ Failed to create config: {e}")
        return False

def performance_benchmark():
    """Run a basic performance benchmark."""
    print("\n🏃 Performance Benchmark")
    print("=" * 40)
    
    try:
        import numpy as np
        import pandas as pd
        import time
        
        # NumPy benchmark
        print("⏱️  NumPy array operations...")
        start_time = time.time()
        arr = np.random.random((1000, 1000))
        result = np.dot(arr, arr.T)
        numpy_time = time.time() - start_time
        print(f"   NumPy matrix multiplication: {numpy_time:.3f}s")
        
        # Pandas benchmark
        print("⏱️  Pandas DataFrame operations...")
        start_time = time.time()
        df = pd.DataFrame(np.random.random((10000, 10)))
        result = df.groupby(df.index % 100).mean()
        pandas_time = time.time() - start_time
        print(f"   Pandas groupby operation: {pandas_time:.3f}s")
        
        # Overall assessment
        total_time = numpy_time + pandas_time
        if total_time < 2.0:
            print("✅ Excellent performance")
        elif total_time < 5.0:
            print("✅ Good performance")
        else:
            print("⚠️  Performance may be slow")
        
        return total_time
        
    except Exception as e:
        print(f"❌ Benchmark failed: {e}")
        return None

def main():
    """Main optimization analysis function."""
    print("🔬 FractalSemantics GUI Optimization Tool")
    print("=" * 50)
    
    # Check system resources
    resources = check_system_resources()
    
    # Analyze dependencies
    deps_ok = analyze_dependencies()
    
    # Generate recommendations
    recommendations = generate_optimization_recommendations(resources)
    
    # Create optimization config
    config_created = create_optimization_config()
    
    # Run performance benchmark
    benchmark_time = performance_benchmark()
    
    # Summary
    print("\n" + "=" * 50)
    print("📊 OPTIMIZATION SUMMARY")
    print("=" * 50)
    
    print(f"System Memory: {resources['memory_gb']:.1f} GB")
    print(f"CPU Cores: {resources['cpu_cores']}")
    print(f"Disk Free: {resources['disk_free_gb']:.1f} GB")
    print(f"Dependencies: {'✅ OK' if deps_ok else '❌ Issues'}")
    print(f"Config Created: {'✅ Yes' if config_created else '❌ No'}")
    if benchmark_time:
        print(f"Benchmark Time: {benchmark_time:.2f}s")
    
    print("\n💡 Quick Optimization Tips:")
    print("- Use Quick Mode for development and testing")
    print("- Enable parallel execution on multi-core systems")
    print("- Monitor memory usage during large experiments")
    print("- Clear results periodically to free memory")
    print("- Use filters to focus on specific experiments")
    
    if resources['memory_gb'] >= 8 and resources['cpu_cores'] >= 4:
        print("\n🚀 Your system is well-suited for FractalSemantics GUI!")
    else:
        print("\n🔧 Consider the recommendations above for better performance.")

if __name__ == "__main__":
    main()